language: node_js
node_js:
  - '6.2'
  - '6.1'
  - '6'
  - '5.1'
  - '5'
before_install:
  - 'npm install -g npm@latest'
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
