language: node_js
node_js:
  - '6.2'
  - '6.1'
  - '6'
  - '5.1'
  - '5'
before_install:
  - 'npm install -g npm@latest'
  - 'npm install -g coveralls@2'
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov && cat ./coverage/lcov.info | coveralls'
